return {
    Accent = Color3.fromHex("#3498db"), -- biru terang

    AcrylicMain = Color3.fromHex("#0d1117"), -- gelap modern
    AcrylicBorder = Color3.fromHex("#2c3e50"),
    AcrylicGradient = ColorSequence.new(Color3.fromHex("#0d1117"), Color3.fromHex("#0d1117")),
    AcrylicNoise = 0.92,

    TitleBarLine = Color3.fromHex("#2c3e50"),
    Tab = Color3.fromHex("#ecf0f1"),

    Element = Color3.fromHex("#1f2a36"),
    ElementBorder = Color3.fromHex("#34495e"),
    InElementBorder = Color3.fromHex("#3498db"),
    ElementTransparency = 0.85,

    ToggleSlider = Color3.fromHex("#3498db"),
    ToggleToggled = Color3.fromHex("#0d1117"),

    SliderRail = Color3.fromHex("#2980b9"),

    DropdownFrame = Color3.fromHex("#1f2a36"),
    DropdownHolder = Color3.fromHex("#17202a"),
    DropdownBorder = Color3.fromHex("#34495e"),
    DropdownOption = Color3.fromHex("#bdc3c7"),

    Keybind = Color3.fromHex("#1f2a36"),

    Input = Color3.fromHex("#2c3e50"),
    InputFocused = Color3.fromHex("#2c3e50"),
    InputIndicator = Color3.fromHex("#7f8c8d"),

    Dialog = Color3.fromHex("#1c2833"),
    DialogHolder = Color3.fromHex("#0b1a2e"),
    DialogHolderLine = Color3.fromHex("#06131f"),
    DialogButton = Color3.fromHex("#1f2a36"),
    DialogButtonBorder = Color3.fromHex("#34495e"),
    DialogBorder = Color3.fromHex("#2c3e50"),
    DialogInput = Color3.fromHex("#2c3e50"),
    DialogInputLine = Color3.fromHex("#3498db"),

    Text = Color3.fromHex("#ecf0f1"),
    SubText = Color3.fromHex("#95a5a6"),
    Hover = Color3.fromHex("#273746"),
    HoverChange = 0.05
}
